In [4]:
import sqlite3
import pandas as pd

In [2]:
import sqlite3

#Conecta ou cria um banco de dados SQLite chamado 'processos.db'
conexao = sqlite3.connect('resultados_teste.db')

# Cria um cursor para executar comandos SQL
cursor = conexao.cursor()

# Cria a tabela com as colunas definidas
# cursor.execute('''
#     CREATE TABLE IF NOT EXISTS tipo_notas (
#         id_nota INTEGER PRIMARY KEY AUTOINCREMENT,
#         nm_nota VARCHAR (255)
#     )
# ''')

# cursor.execute('''
#     CREATE TABLE IF NOT EXISTS tempo_lecionando (
#         id_range INTEGER PRIMARY KEY AUTOINCREMENT,
#         range_tempo VARCHAR (255)
#     )
# ''')

# cursor.execute('''
#     CREATE TABLE IF NOT EXISTS onde_leciona (
#         id_ensino INTEGER PRIMARY KEY AUTOINCREMENT,
#         nm_ensino VARCHAR (255)
#     )
# ''')

# cursor.execute('''
#     CREATE TABLE IF NOT EXISTS disciplinas (
#         id_disciplina INTEGER PRIMARY KEY AUTOINCREMENT,
#         nm_disciplina VARCHAR (255)
#     )
# ''')

cursor.execute('''
    CREATE TABLE IF NOT EXISTS usuario_disciplinas (
        id_usuario_disciplina INTEGER PRIMARY KEY AUTOINCREMENT,
        id_usuario INT,
        nm_disciplina NVARCHAR
    )
''')

cursor.execute('''
    CREATE TABLE IF NOT EXISTS usuario_onde_leciona (
        id_usuario_onde_leciona INTEGER PRIMARY KEY AUTOINCREMENT,
        id_usuario INT,
        nm_onde_leciona NVARCHAR
        
    )
''')

cursor.execute('''
    CREATE TABLE IF NOT EXISTS resultados (
        id_usuario NVARCHAR PRIMARY KEY,
        num_anos_leciona NVARCHAR,
        nm_materias_extra NVARCHAR,
        questao_1 INT,
        sol_1 INT,
        config_1_1 INT,
        nota_1_1 NVARCHAR,
        config_1_2 INT,
        nota_1_2 NVARCHAR,
        preferencia_1 NVARCHAR,
        texto_1 NVARCHAR,
        questao_2 INT,
        sol_2 INT,
        config_2_1 INT,
        nota_2_1 INT,
        config_2_2 INT,
        nota_2_2 NVARCHAR,
        preferencia_2 NVARCHAR,
        texto_2 NVARCHAR,
        questao_3 INT,
        sol_3 INT,
        config_3_1 INT,
        nota_3_1 NVARCHAR,
        config_3_2 INT,
        nota_3_2 NVARCHAR,
        preferencia_3 NVARCHAR,
        texto_3 NVARCHAR
    )
''')

# disciplinas = [
#     ("Introdução à Programação",), ("Banco de Dados",), ("Algoritmos e Estruturas de Dados",), 
#     ("Redes de Computadores",), ("Inteligência Artificial",), ("Cibersegurança",), ("Computação Gráfica",),
#     ("Engenharia de Software",), ("Sistemas Operacionais",), ("Programação Orientada a Objetos",)
#     ]

# cursor.executemany("INSERT INTO disciplinas (nm_disciplina) VALUES (?)", disciplinas)

# tipo_notas = [
#     ("Concordo Totalmente",), ("Concordo Parcialmente",), ("Indiferente ou Neutro",),
#     ("Discordo Parcialmente",), ("Discordo Totalmente",)
# ]

# cursor.executemany("INSERT INTO tipo_notas (nm_nota) VALUES (?)", tipo_notas)

# tempo_lecionando = [
#     ("0-5 anos",), ("6-10 anos",), ("11-15 anos",), ("16-20 anos",), ("Mais de 20 anos",)]

#cursor.executemany("INSERT INTO tempo_lecionando (range_tempo) VALUES (?)", tempo_lecionando)

# onde_leciona = [
#     ("Ensino Básico e Tecnológico",), ("Ensino Superior",), ("Pós-Graduação Lato Sensu (MBA)",), ("Pós-graduação Stricto Sensu",)
#     ]

# cursor.executemany("INSERT INTO onde_leciona (nm_ensino) VALUES (?)", onde_leciona)

# Confirma a criação da tabela
conexao.commit()

# Fecha a conexão com o banco de dados
conexao.close()

In [9]:
conexao = sqlite3.connect("resultados_teste(1).db")
df_resultados = pd.read_sql_query("SELECT * FROM resultados", conexao)
conexao.close()

In [10]:
df_resultados

,id_usuario,num_anos_leciona,nm_materias_extra,questao_1,sol_1,config_1_1,nota_1_1,config_1_2,nota_1_2,preferencia_1,...,preferencia_2,texto_2,questao_3,sol_3,config_3_1,nota_3_1,config_3_2,nota_3_2,preferencia_3,texto_3
0,9aea1d59-f43a-412f-9880-49a80233b2f3,11-15 anos,,2,4,2,Concordo Totalmente,3,Concordo Totalmente,Comentário 1,...,None,None,None,None,None,None,None,None,None,None
1,49ebcdb0-5ef3-424e-b1fa-493d10fbd8ed,Mais de 20 anos,,1,4,3,Concordo Totalmente,2,Concordo Totalmente,Comentário 1,...,None,None,None,None,None,None,None,None,None,None
2,56fbff96-66db-4a25-8cfe-edd9240f787a,11-15 anos,,2,3,3,Concordo Totalmente,2,Concordo Totalmente,Comentário 1,...,None,None,None,None,None,None,None,None,None,None
3,058a9de7-7924-48fa-9788-bf0cc0eaad8b,0-5 anos,,2,1,1,Concordo Totalmente,3,Concordo Totalmente,Comentário 1,...,None,None,None,None,None,None,None,None,None,None
4,4f9943c5-194e-4ae1-b767-f54cbf955227,0-5 anos,,2,1,3,Concordo Totalmente,2,Concordo Totalmente,Comentário 1,...,None,None,None,None,None,None,None,None,None,None
5,e563b6f2-95d3-4beb-b093-bbb1a65b8956,0-5 anos,,2,3,1,Concordo Totalmente,3,Concordo Totalmente,Comentário 1,...,None,None,None,None,None,None,None,None,None,None
6,dd57963a-f33e-43ad-ab9b-4b9b20e4e417,0-5 anos,,2,2,2,Concordo Totalmente,1,Concordo Totalmente,Comentário 1,...,None,None,None,None,None,None,None,None,None,None
7,a3219490-5d5a-43a1-b875-38881e023aef,0-5 anos,,2,3,1,Concordo Totalmente,3,Concordo Totalmente,Comentário 1,...,None,None,None,None,None,None,None,None,None,None
8,3aa871a7-0e98-49c1-88b7-7ab733146504,0-5 anos,,2,3,3,Concordo Totalmente,1,Concordo Totalmente,Comentário 1,...,None,None,None,None,None,None,None,None,None,None
9,9539b5d0-ff8b-485b-8c43-20adf78ac5dc,0-5 anos,,2,3,1,Concordo Totalmente,3,Concordo Totalmente,Comentário 1,...,None,None,None,None,None,None,None,None,None,None
10,91e9d756-06d0-4b55-9718-cb0bffc7d19c,0-5 anos,,2,3,1,Concordo Totalmente,2,Concordo Totalmente,Comentário 1,...,None,None,None,None,None,None,None,None,None,None
11,82034c8b-bbb4-4460-81bd-940ba96cd8ff,Mais de 20 anos,,1,1,1,Concordo Totalmente,3,Concordo Totalmente,Comentário 1,...,None,None,None,None,None,None,None,None,None,None

In [7]:
conexao = sqlite3.connect("dados_origem.db")
df_comentarios = pd.read_sql_query("SELECT * FROM comentarios_modelo", conexao)
conexao.close()

In [8]:
df_comentarios

,id,problema,solucao,prompt,comentario_llm,vezes_sorteado
0,1,1,1,1,Comentário sobre a solução:\n\nA legibilidade ...,0
1,2,1,1,2,{Legibilidade: 8/10}\n\nA indentação está corr...,0
2,3,1,1,3,**Comentário sobre a solução**\n\nA legibilida...,0
3,4,1,2,1,**Legibilidade do código:**\n\n* A indentação ...,0
4,5,1,2,2,"A legibilidade do código é boa, a indentação e...",0
5,6,1,2,3,Aqui estão minhas recomendações e sugestões:\n...,0
6,7,1,3,1,Uma boa oportunidade para avaliar a legibilida...,0
7,8,1,3,2,{Legibilidade: 8/10}\n\nA legibilidade do códi...,0
8,9,1,3,3,"Comentário:\n\nA legibilidade do código é boa,...",0
9,10,1,4,1,Uma boa oportunidade para trabalhar na legibil...,0
10,11,1,4,2,"{A legibilidade do código é boa, mas há alguns...",0
11,12,1,4,3,Aqui estão minhas observações sobre a solução:...,0
12,13,1,5,1,Comentário:\n\n* A legibilidade do código é ba...,0
13,14,1,5,2,{A legibilidade do código é baixa devido à fal...,0
14,15,1,5,3,Aqui estão minhas observações e recomendações:...,0
15,16,2,1,1,Comentário:\n\nA solução apresentada é uma fun...,0
16,17,2,1,2,{Comentário da solução}\n\nLegibilidade do cód...,0
17,18,2,1,3,**Legibilidade do código:**\n\n* A indentação ...,0
18,19,2,2,1,Aqui estão minhas sugestões de melhorias para ...,0
19,20,2,2,2,"A legibilidade do código é boa, pois as variáv...",0
20,21,2,2,3,Aqui estão minhas sugestões e recomendações pa...,0
21,22,2,3,1,Comentário: A função `avioes` determina se a q...,0
22,23,2,3,2,{Avaliação da solução}\n\nLegibilidade do códi...,0
23,24,2,3,3,**Comentário**: A função `avioes` calcula se a...,0
24,25,2,4,1,Comentário: A função `avioes` verifica se a qu...,0
25,26,2,4,2,{Comentário sobre a legibilidade do código}\nA...,0
26,27,2,4,3,Comentário: A função `avioes` é responsável po...,0
27,28,2,5,1,Comentário: A função `avioes` calcula se a qua...,0
28,29,2,5,2,{Avaliação da solução}\n\nLegibilidade do códi...,0
29,30,2,5,3,Aqui estão minhas sugestões e recomendações pa...,0

In [56]:
import pandas as pd

# Conectando ao banco de dados
conexao = sqlite3.connect('resultados_teste.db')

# Executando uma consulta SQL e importando para DataFrame
query = "SELECT * FROM disciplinas"
df_disciplinas = pd.read_sql_query(query, conexao)

query = "SELECT * FROM onde_leciona"
df_onde_leciona = pd.read_sql_query(query, conexao)

query = "SELECT * FROM tempo_lecionando"
df_tempo_lecionando = pd.read_sql_query(query, conexao)

query = "SELECT * FROM tipo_notas"
df_tipo_notas = pd.read_sql_query(query, conexao)

# Fechando a conexão
conexao.close()

In [60]:
df_disciplinas

   id_disciplina                     nm_disciplina
0              1          Introdução à Programação
1              2                    Banco de Dados
2              3  Algoritmos e Estruturas de Dados
3              4             Redes de Computadores
4              5           Inteligência Artificial
5              6                    Cibersegurança
6              7                Computação Gráfica
7              8            Engenharia de Software
8              9             Sistemas Operacionais
9             10   Programação Orientada a Objetos